# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  segment_write_key: <%= ENV['SEGMENT_WRITE_KEY'] %>
  sentry_public_dsn: <%= ENV['SENTRY_PUBLIC_DSN'] %>

development:
  <<: *common
  secret_key_base: 7bd7832d22fa305afccf095d248da5f4f6abda1a61344aad69b101d82a49fdb293bd59a2a17ac0a8a52ff8269d8703a0b2fe22e349774c542cb769e22f1a5aa8

test:
  <<: *common
  secret_key_base: 61f7546dbf2ec78febb914c44f79eec24e19ebf268a65e566e0c8085c80ce4b46cce8b1b42599835fe051b2f28db92e22abc7b02bad7b976d9474688c0d0647f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
